include $HOME/.cache/wal/colors-kitty.conf
include $HOME/.cache/wal/colors-kitty-extra.conf
# include Night Owl.conf

confirm_os_window_close 0

url_style straight

placement_strategy top

map alt+k       scroll_line_up
map alt+j       scroll_line_down
map alt+shift+k scroll_page_up
map alt+shift+j scroll_page_down

font_size 14
font_family JetBrainsMono Nerd Font
map ctrl+equal change_font_size all +1.0
map ctrl+minus change_font_size all -1.0
map ctrl+0     change_font_size all 0
disable_ligatures always

scrollback_pager nvim --cmd 'let g:minimal=v:true' --cmd 'set eventignore=FileType' +'nnoremap q ZQ' +'call nvim_open_term(0, {})' +'set nomodified nolist' +'$' -
map --allow-fallback=shifted,ascii kitty_mod+space show_scrollback

background_opacity 0.9
# dynamic_background_opacity yes
# map --allow-fallback=shifted,ascii kitty_mod+o set_background_opacity +0.1
# map --allow-fallback=shifted,ascii kitty_mod+i set_background_opacity -0.1
# map --allow-fallback=shifted,ascii kitty_mod+p set_background_opacity default
