j seek -5 exact
Alt+j seek -30 exact
k cycle pause
l seek 5 exact
Alt+l seek 30 exact

- add video-zoom -0.1
= add video-zoom 0.1

Ctrl+- add audio-delay -0.05
Ctrl+= add audio-delay 0.05

Ctrl+h add video-pan-x -0.1
Ctrl+j add video-pan-y 0.1
Ctrl+k add video-pan-y -0.1
Ctrl+l add video-pan-x 0.1
Ctrl+BS set video-pan-x 0; set video-pan-y 0; set video-zoom 0

y ab-loop

[ add speed -0.1
] add speed 0.1
