# ------------ [ C ] ------------
---
If:
  PathMatch: [.*\.c, .*\.h]
CompileFlags:
  Compiler: gcc
  Add: [-xc, -std=c17, -Wall]

Diagnostics:
  UnusedIncludes: None
  #Suppress: -Wunused
...

# ------------ [ C++ ] ------------
---
If:
  PathMatch: [.*\.cpp, .*\.hpp]
CompileFlags:
  Compiler: g++
  Add: [-xc++, -std=c++17, -Wall]

Diagnostics:
  UnusedIncludes: None
  #Suppress: -Wunused
...
