# ------------ [ C ] ------------
---
If:
  PathMatch: [.*\.c, .*\.h]
CompileFlags:
  Compiler: gcc
  Add: [-xc, -Wall, -Wextra]

# Diagnostics:
  # UnusedIncludes: None
  # Suppress: -Wunused
...

# ------------ [ C++ ] ------------
---
If:
  PathMatch: [.*\.cpp, .*\.hpp]
CompileFlags:
  Compiler: g++
  Add: [-xc++, -Wall, -Wextra]

# Diagnostics:
#   UnusedIncludes: None
#   Suppress: -Wunused
...
