input {
	kb_layout = us
	kb_variant =
	kb_model =
	kb_options = caps:swapescape
	kb_rules =

	repeat_rate = 60
	repeat_delay = 250

	follow_mouse = 1

	sensitivity = 0
	force_no_accel = false

	touchpad {
		natural_scroll = true
		scroll_factor = 0.1
	}
}

gestures {
	workspace_swipe = true
}

# use `hyprctl devices` to get device names
device {
	name = 2.4g-mouse-1
	sensitivity = -1
}

device {
	name = elan0524:00-04f3:3215-touchpad
	sensitivity = 1
	accel_profile = flat
}
