$scripts = ~/.scripts

$terminal = alacritty
$floatingTerminal = [float; size (monitor_w*0.62) (monitor_h*0.65); center] $terminal
$fileManager = thunar
$fileManagerTui = $floatingTerminal -e yazi
$menu = rofi -x11 -show combi
$menuPrime = prime-run $menu
$waybarControl = $scripts/wbctl.sh
$browser = firefox
$screenlock = hyprlock
$musicPlayer = $terminal --class rmpc -e rmpc
$pywalctl = $scripts/pywalctl.sh
$changeOpacity = $scripts/ala-opc.sh
$powerMenu = $scripts/powermenu.sh
$prop = $scripts/prop.sh
$editMenu = $scripts/edit.sh
$ocr = $scripts/ocr.sh
$toggleReverb = $scripts/toggleReverb.sh
$screenshot = $scripts/screenshot.sh
$colorpicker = hyprpicker -a
$qrscanner = $scripts/qrscan.sh
$emojiselector = rofimoji
$unicodemenu = $scripts/unicodemenu.sh
$clock = $floatingTerminal --class clock -e $scripts/clock.sh
$whiteboard = [float] $scripts/lorien.sh
$editClipboard = $scripts/editclipboard.sh
$viewPywalColors = $floatingTerminal -e nvim -R ~/.cache/wal/colors-readable.txt
$experimentMenu = $scripts/experiment.sh
$searchBook = $scripts/searchbook.sh
$changeVar = $scripts/hyprvars.sh
$cpulimiter = $scripts/cpulimiter.sh
