$scripts = ~/.scripts

$terminal = alacritty
$floatingTerminal = [float; size 62% 65%] $terminal
$fileManager = thunar
$fileManagerTui = $floatingTerminal -e yazi
$menu = rofi -show combi
$waybarControl = $scripts/wbctl.sh
$browser = firefox
$screenlock = hyprlock
$musicPlayer = $terminal --class rmpc -e rmpc
$changeWallpaper = $scripts/pickWallpaper.sh
$changeWalBackend = $scripts/pickWalBackend.sh
$changeWalSaturation = $scripts/pickWalSaturation.sh
$changeOpacity = $scripts/ala-opc.sh
$powerMenu = $scripts/powermenu.sh
$prop = $scripts/prop.sh
$editMenu = $scripts/edit.sh
$ocr = $scripts/ocr.sh
$toggleReverb = $scripts/toggleReverb.sh
$screenshot = $scripts/screenshot.sh
$colorpicker = hyprpicker -a
$qrscanner = $scripts/qrscan.sh
$emojiselector = rofimoji
$clock = $floatingTerminal --class clock -e $scripts/clock.sh
$whiteboard = [float] $scripts/lorien.sh
$editClipboard = $scripts/editclipboard.sh
$viewPywalColors = $floatingTerminal -e nvim -R ~/.cache/wal/colors-readable.txt
$experimentMenu = $scripts/experiment.sh
$searchBook = $scripts/searchbook.sh
