# Ignore maximize requests from apps. You'll probably like this.
windowrulev2 = suppressevent maximize, class:.*

# Fix some dragging issues with XWayland
windowrulev2 = nofocus, class:^$, title:^$, xwayland:1, floating:1, fullscreen:0, pinned:0

windowrulev2 = noanim, class:^ueberzugpp.*$

windowrulev2 = float, class:^pickimg$

windowrulev2 = float, title:(^edit.sh$)|(^fileManagerTui$)|(^rmpc$)
windowrulev2 = size 70% 70%, title:(^edit.sh$)|(^fileManagerTui$)|(^rmpc$)

windowrulev2 = float, class:(^python3$)
windowrulev2 = size 70% 70%, class:(^python3$)

windowrulev2 = float, class:(^T|thunar$)
windowrulev2 = size 70% 70%, class:(^T|thunar$)
windowrulev2 = opacity 0.8, class:(^T|thunar$)
