$scripts = ~/.scripts

$terminal = alacritty
$floatingTerminal = [float; size 60% 60%] $terminal
$fileManager = thunar
$fileManagerTui = $terminal --title fileManagerTui -e yazi
$menu = rofi -show combi
$waybarControl = $scripts/wbctl.sh
$browser = firefox
$screenlock = hyprlock
$musicPlayer = $terminal --title rmpc -e rmpc
$changeWallpaper = $scripts/pickWallpaper.sh
$changeWalBackend = $scripts/pickWalBackend.sh
$changeOpacity = $scripts/ala-opc.sh
$powerMenu = $scripts/powermenu.sh
$prop = $scripts/prop.sh
$editMenu = $scripts/edit.sh
$ocr = $scripts/ocr.sh
$toggleReverb = $scripts/toggleReverb.sh
$screenshot = $scripts/screenshot.sh
$colorpicker = hyprpicker -a
$qrscanner = $scripts/qrscan.sh
