###########################
####  HYPRLAND CONFIG  ####
###########################

source = hyprland-monitors.conf # Monitors
source = hyprland-programs.conf # Programs
source = ~/.cache/wal/colors-hypr.conf # Pywal Colors
source = hyprland-autostart.conf # Autostart
source = hyprland-fixes.conf # Fixes
source = hyprland-decorations.conf # Look and Feel
source = hyprland-animations.conf # Animations
source = hyprland-input.conf # Input
source = hyprland-binds.conf # Keybindings
source = hyprland-windowrules.conf # Window rules
