# Ignore maximize requests from apps. You'll probably like this.
windowrulev2 = suppressevent maximize, class:.*

# Fix some dragging issues with XWayland
windowrulev2 = nofocus, class:^$, title:^$, xwayland:1, floating:1, fullscreen:0, pinned:0

windowrulev2 = noanim, class:^ueberzugpp.*$

windowrulev2 = float, class:^pickimg$

$classes = (^edit.sh$)|(^rmpc$)|(^python3$)|(^T|thunar$)|(^Lorien$)|(^editClipboard$)|(^experiment.sh$)
windowrulev2 = float, class:$classes
windowrulev2 = size 70% 70%, class:$classes
windowrulev2 = opacity 0.8, class:(^T|thunar$)
windowrulev2 = opacity 0.7, class:(^Lorien$)
windowrulev2 = noblur, class:(^Lorien$)
