windowrule {
    # Ignore maximize requests from all apps. You'll probably like this.
    name = suppress-maximize-events
    match:class = .*

    suppress_event = maximize
}

windowrule {
    # Fix some dragging issues with XWayland
    name = fix-xwayland-drags
    match:class = ^$
    match:title = ^$
    match:xwayland = true
    match:float = true
    match:fullscreen = false
    match:pin = false

    no_focus = true
}

$editMenu_pattern = (^edit.sh$)
$rmpc_pattern = (^rmpc$)
$python_pattern = (^python3$)
$thunar_pattern = (^T|thunar$)
$lorien_pattern = (^Lorien$)
$editClipboard_pattern = (^editClipboard$)
$experiment_pattern = (^experiment.sh$)
$mpv_pattern = (^mpv$)
$ueberzugpp_pattern = (^ueberzugpp.*$)
$pickimg_pattern = (^pickimg$)

$floating = $editMenu_pattern|$rmpc_pattern|$python_pattern|$thunar_pattern|$lorien_pattern|$editClipboard_pattern|$experiment_pattern|$mpv_pattern

windowrule {
	name = pickimg
	match:class = $pickimg_pattern
	float = true
	center = true
}

windowrule {
	name = ueberzugpp-fix
	match:class = $ueberzugpp_pattern
	float = true
	no_focus = true
	no_anim = true
	border_size = 0
	rounding = 0
}

windowrule {
	name = floating
	match:class = $floating
	float = true
	center = true
	size = (monitor_w*0.7) (monitor_h*0.7)
}

windowrule {
	name = lorien
	match:class = (^Lorien$)
	no_blur = true
	opacity = 0.7
}

windowrule {
	name = thunar
	match:class = (^T|thunar$)
	opacity = 0.8
}
