source = $HOME/.cache/wal/colors-hypr.conf

general {
	hide_cursor = true
}

auth {

}

animations {
	enabled = true
	bezier = quick, 0.15, 0, 0.1, 1
	animation = inputField, 1, 0.2, quick
}

background {
	path = $wallpaper
}

input-field {
	size = 500, 100
}

label {
}
