"$schema" = "https://yazi-rs.github.io/schemas/keymap.json"

[mgr]

prepend_keymap = [
	{ on = "Z",             run = "plugin fzf",                  desc = "Jump to a file/directory via fzf" },
	{ on = "z",             run = "plugin zoxide",               desc = "Jump to a directory via zoxide" },
	{ on = "<C-D>",         run = "remove --permanently",        desc = "Permanently delete selected files" },
	{ on = ["D"],           run = "noop"},
]
