# https://github.com/sxyazi/yazi/tree/shipped/yazi-config/preset
[manager]
show_hidden = true
sort_by = "natural"
sort_reverse = false

[opener]
edit = [
	{ run = 'nvim "$@"', block = true, for = "unix" }
]
open = [
	{ run = 'xdg-open "$@"', orphan = true, desc = "Open" }
]
