# https://github.com/sxyazi/yazi/tree/shipped/yazi-config/preset
#:schema https://yazi-rs.github.io/schemas/yazi.json

[mgr]

show_hidden = true
sort_by = "natural"
sort_reverse = false

[opener]

edit = [
	{ run = 'nvim %s', block = true, for = "unix" }
]

open = [
	{ run = 'xdg-open %s', orphan = true, desc = "Open" }
]
