$wallpaper		= {wallpaper}

$background		= rgb({background.rgb})
$foreground		= rgb({foreground.rgb})
$cursor			= rgb({cursor.rgb})

$black			= rgb({color0.rgb})
$red			= rgb({color1.rgb})
$green			= rgb({color2.rgb})
$yellow			= rgb({color3.rgb})
$blue			= rgb({color4.rgb})
$magenta		= rgb({color5.rgb})
$cyan			= rgb({color6.rgb})
$white			= rgb({color7.rgb})

$brightBlack	= rgb({color8.rgb})
$brightRed		= rgb({color9.rgb})
$brightGreen	= rgb({color10.rgb})
$brightYellow	= rgb({color11.rgb})
$brightBlue		= rgb({color12.rgb})
$brightMagenta	= rgb({color13.rgb})
$brightCyan		= rgb({color14.rgb})
$brightWhite	= rgb({color15.rgb})
