[general]
import = [
	"~/.cache/wal/colors-alacritty.toml",
	"~/.config/alacritty/alacritty-opacity.toml",
]

[font]
size = 14.0
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
bold = { family = "JetBrainsMono Nerd Font", style = "Bold" }
italic = { family = "JetBrainsMono Nerd Font", style = "Italic" }
bold_italic = { family = "JetBrainsMono Nerd Font", style = "Bold Italic" }

[keyboard]
bindings = [
	{ action = "ToggleViMode", key = "Space", mods = "Control" },
	{ action = "ScrollLineUp", key = "k", mods = "Alt" },
	{ action = "ScrollLineDown", key = "j", mods = "Alt" },
	{ action = "ScrollPageUp", key = "k", mods = "Alt|Shift" },
	{ action = "ScrollPageDown", key = "j", mods = "Alt|Shift" },
]

[mouse]
hide_when_typing = true

[window]
dynamic_padding = true
